### ISSUE TITLE
Server 6.2023.12 supported platform

### ISSUE THREAD

**Issue by kronos72it** [payara/Payara-Documentation#367]
In [reference payara page](https://docs.payara.fish/community/docs/General%20Info/Supported%20Platforms.html) it states support also for JDK 21.01 but if I try to register the serve with NB 19 and JDK 21.01 installed NB wizard tell "Payara Server couldn't be started with JDK 21" 

then where is the trouble ?

**Comment by fturizo** [comment]
@kronos72it, it sounds like you have a problem configuring your Netbeans IDE environment to support JDK 21 but this is not the place to raise ecosystem-related bugs. 
Please raise a detailed report over at https://github.com/fturizo/ecosystem-support/issues

We'll proceed to close this issue as it is not related to the contents of the documentation.
